const links = [
  { link: "/category/smartphones", category: "Smartphone" },
  { link: "/category/skincare", category: "Skincare", },
  { link: "/category/womens-jewellery", category: "Jewellery" },
  { link: "/category/fragrances", category: "Fragrances" },
  { link: "/category/womens-dresses", category: "Women dresses" },
  { link: "/category/mens-shirts", category: "Men shirts" },
  { link: "/category/womens-shoes", category: "Women shoe" },
  { link: "/category/mens-shoes", category: "Men shoe" },
  { link: "/category/laptops", category: "Laptops" },
  { link: "/category/groceries", category: "Groceries" },
  { link: "/category/home-decoration", category: "Home decorations" },
  { link: "/category/furniture", category: "Furniture" },
  { link: "/category/automotive", category: "Automotive" },
  { link: "/category/tops", category: "Tops" },
  { link: "/category/mens-watches", category: "Mens watches" },
  { link: "/category/womens-watches", category: "Womens watches" },
  { link: "/category/sunglasses", category: "Sunglasses" },
  { link: "/category/motorcycle", category: "Motorcycle" },
  { link: "/category/lighting", category: "Lighting" },
]
export default links;
